title: My website
author: Youssef Abdelhalem
email: Yabdelhalem@ebnet.org
description: Website for Mr.Cohens Ap comp sci A class 
theme: minima.
# social links
Instagram_username: youssef_is_my_name
github_username:  YoussefAbdelhalem

show_excerpts: true # set to false to remove excerpts on the homepage
